pipeline {
    agent { 
        node { 
            label ''
        } 
    }

    stages {
        stage('Maven Build & Test') {
            steps {
                sh 'mvn clean package'
            }
        }
    }
}