pipeline {
    agent { 
        node { 
            label ''
        } 
    }

    tools {
        
        maven 'maven3' 
    }

    stages {
        stage('Maven Build & Test') {
            steps {
           
                dir('event-manager-backend') {
                    sh 'mvn clean package'
                }
            }
        }
    }
}